// Auto-generated by `supabase gen types typescript --linked --schema public`.
// Re-run `pnpm supabase:gen-types` whenever the schema changes.
// Helper exports (Profile, Subscription, etc.) are appended at the bottom of
// this file so route/component code has a stable place to import from.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      activity_log: {
        Row: {
          action: string
          created_at: string
          details: string | null
          id: string
          ip_address: unknown
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          details?: string | null
          id?: string
          ip_address?: unknown
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          details?: string | null
          id?: string
          ip_address?: unknown
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      contracts: {
        Row: {
          client_address: string | null
          client_city: string | null
          client_email: string | null
          client_name: string | null
          client_phone: string | null
          client_postal: string | null
          contract_price: number | null
          contract_type: string
          contractor_address: string | null
          contractor_city: string | null
          contractor_email: string | null
          contractor_name: string | null
          contractor_phone: string | null
          contractor_postal: string | null
          contractor_rbq: string | null
          created_at: string
          id: string
          metadata: Json
          pdf_path: string | null
          project_city: string | null
          project_description: string | null
          project_postal: string | null
          project_site: string | null
          status: string
          stripe_checkout_session_id: string | null
          stripe_payment_intent_id: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          client_address?: string | null
          client_city?: string | null
          client_email?: string | null
          client_name?: string | null
          client_phone?: string | null
          client_postal?: string | null
          contract_price?: number | null
          contract_type: string
          contractor_address?: string | null
          contractor_city?: string | null
          contractor_email?: string | null
          contractor_name?: string | null
          contractor_phone?: string | null
          contractor_postal?: string | null
          contractor_rbq?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          pdf_path?: string | null
          project_city?: string | null
          project_description?: string | null
          project_postal?: string | null
          project_site?: string | null
          status?: string
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          client_address?: string | null
          client_city?: string | null
          client_email?: string | null
          client_name?: string | null
          client_phone?: string | null
          client_postal?: string | null
          contract_price?: number | null
          contract_type?: string
          contractor_address?: string | null
          contractor_city?: string | null
          contractor_email?: string | null
          contractor_name?: string | null
          contractor_phone?: string | null
          contractor_postal?: string | null
          contractor_rbq?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          pdf_path?: string | null
          project_city?: string | null
          project_description?: string | null
          project_postal?: string | null
          project_site?: string | null
          status?: string
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contracts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      deleted_users: {
        Row: {
          deleted_at: string
          deleted_by: string | null
          deleted_contract_count: number
          email: string
          notes: string | null
          reason: string | null
        }
        Insert: {
          deleted_at?: string
          deleted_by?: string | null
          deleted_contract_count?: number
          email: string
          notes?: string | null
          reason?: string | null
        }
        Update: {
          deleted_at?: string
          deleted_by?: string | null
          deleted_contract_count?: number
          email?: string
          notes?: string | null
          reason?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          address: string | null
          company_name: string | null
          created_at: string
          email: string
          entity_type: string | null
          first_name: string | null
          full_name: string | null
          head_office: string | null
          ho_city: string | null
          ho_postal: string | null
          id: string
          incorporation_regime: string | null
          ind_city: string | null
          ind_postal: string | null
          last_name: string | null
          logo_url: string | null
          phone: string | null
          rbq: string | null
          rep_name: string | null
          rep_title: string | null
          role: string
          updated_at: string
        }
        Insert: {
          address?: string | null
          company_name?: string | null
          created_at?: string
          email: string
          entity_type?: string | null
          first_name?: string | null
          full_name?: string | null
          head_office?: string | null
          ho_city?: string | null
          ho_postal?: string | null
          id: string
          incorporation_regime?: string | null
          ind_city?: string | null
          ind_postal?: string | null
          last_name?: string | null
          logo_url?: string | null
          phone?: string | null
          rbq?: string | null
          rep_name?: string | null
          rep_title?: string | null
          role?: string
          updated_at?: string
        }
        Update: {
          address?: string | null
          company_name?: string | null
          created_at?: string
          email?: string
          entity_type?: string | null
          first_name?: string | null
          full_name?: string | null
          head_office?: string | null
          ho_city?: string | null
          ho_postal?: string | null
          id?: string
          incorporation_regime?: string | null
          ind_city?: string | null
          ind_postal?: string | null
          last_name?: string | null
          logo_url?: string | null
          phone?: string | null
          rbq?: string | null
          rep_name?: string | null
          rep_title?: string | null
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
      stripe_events: {
        Row: {
          id: string
          processed_at: string
          type: string
        }
        Insert: {
          id: string
          processed_at?: string
          type: string
        }
        Update: {
          id?: string
          processed_at?: string
          type?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          created_at: string
          current_period_end: string | null
          id: string
          plan_type: string
          status: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          plan_type?: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          plan_type?: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// =============================================================================
// Helper aliases used throughout the app — DO NOT regenerate this section.
// =============================================================================

export type Profile = Database['public']['Tables']['profiles']['Row']
export type Subscription = Database['public']['Tables']['subscriptions']['Row']
export type Contract = Database['public']['Tables']['contracts']['Row']
export type ActivityLog = Database['public']['Tables']['activity_log']['Row']

export type WizardEntityType = 'company' | 'individual' | 'other'

export type WizardPaymentMethod =
  | 'lump_sum'
  | 'single_payment_completion'
  | 'progress_payments'
  | 'milestone_payments'
  | 'time_and_materials'

export type WizardInvoiceFrequency = 'weekly' | 'bi_weekly' | 'monthly'

export type WizardPaymentDueDays = 0 | 5 | 15 | 30 | 45 | 60

export interface ContractMetadata {
  // === Identity ===
  project_name?: string
  language?: 'en' | 'fr'
  role?: 'client' | 'contractor' | 'gc' | 'subcontractor'
  form_type?: 'client-contractor' | 'gc-subcontractor'
  logo_url?: string
  guest_session_id?: string

  // === Party entity types (so PDF can pick the right legal phrasing) ===
  my_entity_type?: WizardEntityType
  other_entity_type?: WizardEntityType

  // === Schedule ===
  start_date?: string
  end_date?: string
  sign_date?: string
  duration_value?: number
  duration_unit?: 'days' | 'weeks' | 'months'

  // === Materials & description ===
  material_provider?: 'contractor' | 'client' | 'shared'

  // === Payment ===
  payment_method?: WizardPaymentMethod | string
  payment_method_label?: string
  time_materials_description?: string
  invoice_frequency?: WizardInvoiceFrequency
  payment_due_days?: WizardPaymentDueDays | number
  advance_payment?: boolean
  advance_payment_amount?: number

  // === Late + warranty + holdback + bond + escalation ===
  late_interest?: number
  recovery_penalty?: boolean
  warranty_months?: number
  holdback?: boolean
  holdback_pct?: number
  insurance_amount?: number
  bond?: boolean
  bond_pct?: number
  escalation?: boolean
  escalation_pct?: number

  // === Acceptance + suspension rules (new in v2 spec) ===
  inspection_period_days?: number
  suspension_request_adjustment_days?: number
  suspension_terminate_days?: number
  suspension_resume_claim_days?: number

  // === Misc ===
  extra_clauses?: string

  [key: string]: Json | undefined
}

export function isProActive(sub: Subscription | null | undefined): boolean {
  if (!sub) return false
  return (
    sub.status === 'active' &&
    sub.plan_type === 'unlimited_monthly' &&
    (!sub.current_period_end ||
      new Date(sub.current_period_end) > new Date())
  )
}
